//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPractice.AppConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int ID { get; set; }
        public int IDUser { get; set; }
        public int IDProduct { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual User User { get; set; }
    }
}
